# Generated by Django 5.0.6 on 2024-06-24 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TODO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=52)),
                (
                    "status",
                    models.CharField(
                        choices=[("C", "COMPLETED"), ("P", "PENDING")], max_length=2
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("1", "LOW"), ("2", "MID"), ("3", "HIGH")],
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
